# Generated by Django 4.2.5 on 2023-09-22 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0002_student_status'),
        ('driver', '0003_driver_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_amount', models.IntegerField()),
                ('month_of_fee', models.DateField(null=True)),
                ('date_of_fee_issue', models.DateField()),
                ('due_date_of_fee', models.DateField(null=True)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('date_of_submission', models.DateField(null=True)),
                ('driver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driver.driver')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
    ]
