# Generated by Django 4.2.5 on 2023-09-26 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='Owner_Fee',
            field=models.IntegerField(default=0),
        ),
    ]
