# Generated by Django 4.2.5 on 2023-09-26 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0006_alter_fee_owner_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fee',
            name='Owner_Fee',
        ),
        migrations.AddField(
            model_name='fee',
            name='Owner_profit',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
