# Generated by Django 4.1.7 on 2023-09-26 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0007_remove_fee_owner_fee_fee_owner_profit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fee',
            name='Owner_profit',
        ),
    ]
