# Generated by Django 4.2.5 on 2023-09-26 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0010_fee_date_of_fee_issue_fee_date_of_submission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='Owner_fee',
            field=models.IntegerField(default=0),
        ),
    ]
