# Generated by Django 4.2.5 on 2023-09-14 17:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('driver', '0002_driver_fee_amount'),
        ('student', '0002_student_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complain_content', models.TextField()),
                ('time_of_complain', models.DateTimeField(default=django.utils.timezone.now)),
                ('day_of_complain', models.DateField(default=django.utils.timezone.now)),
                ('owner_approval', models.CharField(default='No', max_length=3)),
                ('driver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='driver.driver')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='student.student')),
            ],
        ),
    ]
