# Generated by Django 4.2.5 on 2023-09-14 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_status'),
        ('shared_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='driver_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student'),
        ),
    ]
