# Generated by Django 4.1.7 on 2023-09-17 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_app', '0003_complaint_owner_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='owner_approval',
            field=models.CharField(default='Pending', max_length=3),
        ),
    ]
