# Generated by Django 4.1.7 on 2023-09-19 15:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0003_driver_status'),
        ('shared_app', '0004_alter_complaint_owner_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='owner_approval',
            field=models.CharField(default='Pending', max_length=7),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='time_of_complain',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='fee_inc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('amount', models.PositiveBigIntegerField()),
                ('time_of_complain', models.TimeField(default=django.utils.timezone.now)),
                ('day_of_complain', models.DateField(default=django.utils.timezone.now)),
                ('owner_approval', models.CharField(default='Pending', max_length=7)),
                ('owner_comments', models.TextField(default='-')),
                ('Driver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driver.driver')),
            ],
        ),
        migrations.CreateModel(
            name='delay_req',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('time', models.TimeField()),
                ('date', models.DateField()),
                ('time_of_complain', models.TimeField(default=django.utils.timezone.now)),
                ('day_of_complain', models.DateField(default=django.utils.timezone.now)),
                ('owner_approval', models.CharField(default='Pending', max_length=7)),
                ('owner_comments', models.TextField(default='-')),
                ('Driver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driver.driver')),
            ],
        ),
    ]
