# Generated by Django 4.1.7 on 2023-09-20 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_app', '0006_alter_fee_inc_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee_inc',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
