# Generated by Django 4.2.5 on 2023-09-09 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='fee_amount',
            field=models.IntegerField(default=1500),
        ),
    ]
